# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       libXScrnSaver
Summary:    X.Org X11 libXss runtime library
Version:    1.2.1
Release:    1
Group:      System/Libraries
License:    MIT
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/lib/%{name}-%{version}.tar.bz2
Source100:  libXScrnSaver.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(xext)
BuildRequires:  pkgconfig(scrnsaverproto) >= 1.2
BuildRequires:  pkgconfig(xextproto)


%description
X11 Screen Saver extension client library



%package devel
Summary:    X.Org X11 libXScrnSaver development package
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
X11 Screen Saver extension client development library



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig





%files
%defattr(-,root,root,-)
# >> files
%{_libdir}/libXss.so.1
%{_libdir}/libXss.so.1.0.0
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%{_libdir}/libXss.so
%dir %{_libdir}/pkgconfig
%{_libdir}/pkgconfig/xscrnsaver.pc
%{_includedir}/X11/extensions/scrnsaver.h
%{_mandir}/man3/*.3*
# << files devel

